language: sh

git:
  depth: false

sudo: required

matrix:
  include:
    - name: "GCC7" 
      env:
        - GCC_VERSION="7"
        - HUB="cmbant/docker-gcc-build:gcc7"
        - COMMAND="/bin/bash -c /forutils/tests/run_tests.sh"
    - name: "GCC8"
      env:
        - GCC_VERSION="8"
        - HUB="cmbant/docker-gcc-build:gcc8"
        - COMMAND="/bin/bash -c /forutils/tests/run_tests.sh"
    - name: "GCC9"
      env:
        - GCC_VERSION="9"
        - HUB="cmbant/docker-gcc-build:gcc9"
        - COMMAND="/bin/bash -c /forutils/tests/run_tests.sh"
    - name: "trunk"
      env:
        - GCC_VERSION="trunk"
        - HUB="cmbant/docker-gcc-build:devel"
        - COMMAND="-c /forutils/tests/run_tests.sh"
 
services:
  - docker

before_install:
  - docker pull $HUB

install:
  - chmod +x tests/run_tests.sh
     
script:
  - docker run -v $(pwd):/forutils -t $HUB $COMMAND


